#!/usr/bin/env python3
"""Render the committed evidence JSON as a readable ``evidence/RUN_LOG.md``.

The Markdown is a view, not a source: every line comes from the JSON files under
``evidence/`` and can be regenerated with this script.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = ROOT / "evidence"

_GROUP_TITLES = {
    "discovery": "Discovery (LLM in the loop)",
    "validation": "Validation replay (draft, different customer, oracle-checked)",
    "replay_before": "Replay, no model: before the deposit",
    "replay_after": "Replay, no model: after a $5.00 deposit",
    "replay_outcomes": "Replay, no model: error and business-outcome cases",
    "handoff_replay": "Replay blocked by an unexpected dialog, then handed to a human",
}


def _load(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def _records(package: Path) -> list[dict]:
    index = _load(package / "index.json")
    return [_load(ROOT / entry["path"]) | {"_group": entry["group"]} for entry in index["records"]]


def _event_line(event: dict) -> str:
    parts = [event["event_type"]]
    for key in ("step_id", "state", "reason_code", "effect_state"):
        if event.get(key):
            parts.append(f"{key}={event[key]}")
    if event.get("duration_ms") is not None:
        parts.append(f"{event['duration_ms']}ms")
    return " · ".join(parts)


def _run_block(record: dict) -> list[str]:
    run = record["run"]
    lines = [
        f"#### `{run['run_alias']}` — {run['mode']} → **{run['state']}** ({run['outcome_code']})",
        "",
        f"model: `{run['model_id'] or 'none'}` · browser: {run['browser_version']} · "
        f"snapshots: {len(record['snapshots'])}",
        "",
        "```text",
    ]
    lines += [_event_line(event) for event in record["events"]]
    lines += ["```", ""]
    for snapshot in record["snapshots"]:
        lines.append(
            f"- snapshot `{snapshot['snapshot_id']}`: route `{snapshot['safe_route']}`, "
            f"page state `{snapshot['page_state']}`, {snapshot['visible_control_count']} visible controls"
        )
    if record["snapshots"]:
        lines.append("")
    return lines


def _decisions(path: Path) -> list[str]:
    data = _load(path)
    lines = ["### What the model saw and decided", ""]
    for item in data["decisions"]:
        observed = item["observed"]
        offered = ", ".join(f"`{c['safe_name']}`" for c in observed["offered_controls"]) or "none"
        lines.append(
            f"**Decision {item['decision']}** — page `{observed['route']}` / `{observed['page_state']}`; "
            f"offered: {offered}"
        )
        signals = ", ".join(f"{k}={v}" for k, v in observed["signals"].items())
        lines.append(f"- signals: {signals}")
        if "rejected" in item:
            lines.append(f"- reply rejected before any action: `{item['rejected']['code']}`")
        else:
            chose = item["chose"]
            target = f" `{chose['control_safe_name']}`" if chose["control_safe_name"] else ""
            lines.append(f"- chose **{chose['operation']}**{target} (`{chose['reason_code']}`)")
            lines.append(f"- why: “{chose['rationale']}”")
            usage = item["usage"]
            lines.append(f"- tokens: {usage['input_tokens']} in / {usage['output_tokens']} out")
        lines.append("")
    return lines


def render() -> str:
    lifecycle = _load(EVIDENCE / "live_lifecycle.json")
    handoff = _load(EVIDENCE / "handoff_run" / "handoff_summary.json")
    out = [
        "# Run log",
        "",
        "Generated by `scripts/render_evidence_log.py` from the JSON in this folder. "
        "Values such as account numbers, balances, names, and credentials are never "
        "recorded; runs are identified by random aliases.",
        "",
        "## 1. Live discovery → artifact → replay",
        "",
        f"- provider: `{lifecycle['provider']['mode']}`, model `{lifecycle['provider']['model_id']}`, "
        f"{lifecycle['provider']['discovery_decisions']} model call(s)",
        f"- artifact: `{lifecycle['artifact']['reference']}` "
        f"(`{lifecycle['artifact']['digest'][:19]}…`) → `{lifecycle['artifact']['path']}`",
        f"- target: ParaBank `{lifecycle['target']['upstream_commit'][:12]}` on loopback",
        f"- replays: {lifecycle['replay']['successful_replays']} successful across "
        f"{lifecycle['replay']['customers']} unseen customers, model calls during replay: "
        f"{lifecycle['replay']['provider_calls']}, balance change observed: "
        f"{lifecycle['replay']['balance_change_observed']}",
        "",
    ]
    out += _decisions(ROOT / lifecycle["discovery_decisions"]["path"])
    out += [
        "### Error and business-outcome replays (one reused session, in order)",
        "",
        "| case | status | code | failed step | outputs returned |",
        "|---|---|---|---|---|",
    ]
    for case in lifecycle["outcome_replays"]:
        failure = case["failure"] or {}
        code = failure.get("reason_code") or case["code"]
        out.append(
            f"| {case['case']} | {case['status']} | `{code}` | {failure.get('step_id') or '—'} "
            f"| {case['outputs_returned']} |"
        )
    out.append("")
    current = None
    for record in _records(EVIDENCE / "live_run"):
        if record["_group"] != current:
            current = record["_group"]
            out += [f"### {_GROUP_TITLES.get(current, current)}", ""]
        out += _run_block(record)

    out += ["## 2. Human handoff on the same live session", ""]
    request = handoff["intervention_request"]
    action = handoff["operator_action"]
    out += [
        f"- intervention raised at step `{request['step_id']}`, reason `{request['reason']}`, "
        f"same page as automation: {request['same_page_as_automation']}",
        f"- operator action: `{action['category']}` by `{action['performed_by']}` on the same page: "
        f"{action['same_page_as_automation']}; dialog present before/after: "
        f"{action['before']['dialog_present']}/{action['after']['dialog_present']}",
        f"- result after resume: **{handoff['result']['status']}**, oracle match: "
        f"{handoff['result']['independent_oracle_match']}",
        "",
        "| t (ms) | event | details |",
        "|---:|---|---|",
    ]
    for entry in handoff["timeline"]:
        details = ", ".join(f"{k}={v}" for k, v in entry.items() if k not in {"t_ms", "kind"})
        out.append(f"| {entry['t_ms']} | {entry['kind']} | {details} |")
    out.append("")
    for record in _records(EVIDENCE / "handoff_run"):
        out += _run_block(record)
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    (EVIDENCE / "RUN_LOG.md").write_text(render(), encoding="utf-8")
    print("wrote evidence/RUN_LOG.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
